"""
Registry of all 78 Enterprise OpenSpec skills.

Each entry is compact, domain-specific metadata. engine.py expands it into a
full skill package. Keep entries focused: the value is the *domain-specific*
focus areas, deliverables, anti-patterns, templates and metrics — the OpenSpec
scaffolding around them is shared.
"""

CATEGORIES = {
    "product": "Product",
    "architecture": "Architecture",
    "frontend": "Frontend",
    "backend": "Backend",
    "ai": "AI & Data",
    "testing": "Testing & Quality",
    "devops": "DevOps & Platform",
    "security": "Security & Compliance",
    "maintenance": "Maintenance & Operations",
}

# Registry: category -> { slug: {...} }
# Keys per skill:
#   t  title
#   d  one-line description
#   p  purpose paragraph
#   f  focus areas (list)
#   dl deliverables (list)
#   ap anti-patterns (list)
#   tpl templates: list of (slug, title)
#   m  success metrics (optional list)

R = {}

def add(cat, slug, t, d, p, f, dl, ap, tpl, m=None):
    R.setdefault(cat, {})[slug] = dict(t=t, d=d, p=p, f=f, dl=dl, ap=ap, tpl=tpl, m=m or [])


# ============================ PRODUCT ============================

add("product", "business-analysis",
    "Business Analysis",
    "Translate business problems into clear, evidence-based opportunities and requirements.",
    "Bridge the gap between business stakeholders and delivery teams by uncovering the real problem, quantifying its value, and framing it as something a team can build against.",
    ["Stakeholder identification and elicitation (interviews, workshops, observation)",
     "Current-state (as-is) vs target-state (to-be) process modeling",
     "Problem framing, root-cause analysis, and value quantification",
     "Business capability and gap analysis",
     "Success metrics and KPI definition tied to business outcomes"],
    ["Business case with quantified problem, value, and options",
     "As-is / to-be process maps",
     "Stakeholder map with concerns and influence",
     "Prioritized business requirements register"],
    ["Jumping to solutions before the problem is understood",
     "Confusing outputs (features shipped) with outcomes (value delivered)",
     "Eliciting from one loud stakeholder and missing the silent majority"],
    [("business-case", "Business Case"), ("stakeholder-map", "Stakeholder Map")],
    ["Time-to-decision on the opportunity", "% of requirements traceable to a business outcome"])

add("product", "market-research",
    "Market Research",
    "Size the market, map competitors, and validate demand before committing to build.",
    "Reduce the risk of building the wrong thing by grounding product bets in evidence about customers, competitors, and market dynamics.",
    ["TAM / SAM / SOM market sizing (top-down and bottom-up)",
     "Competitive landscape and feature/positioning matrices",
     "Customer segmentation, jobs-to-be-done, and demand signals",
     "Pricing and willingness-to-pay analysis",
     "Trend, regulatory, and PESTEL scanning"],
    ["Market sizing model with assumptions",
     "Competitive matrix and positioning map",
     "Segment profiles and JTBD",
     "Go / no-go recommendation with evidence"],
    ["Cherry-picking data that confirms the desired conclusion",
     "Citing TAM without a credible bottom-up cross-check",
     "Treating a few customer interviews as statistically representative"],
    [("market-sizing", "Market Sizing Model"), ("competitive-matrix", "Competitive Matrix")],
    ["Forecast accuracy vs actuals", "Decisions changed by research findings"])

add("product", "prd-generation",
    "PRD Generation",
    "Produce a crisp Product Requirements Document that aligns teams on what and why.",
    "Give engineering, design, and stakeholders a single, reviewable source of truth for what is being built, for whom, why, and how success is measured.",
    ["Problem statement, goals, and non-goals",
     "Personas, user scenarios, and use cases",
     "Functional requirements with priorities (MoSCoW)",
     "Success metrics, instrumentation, and launch criteria",
     "Dependencies, risks, and open questions"],
    ["Approved PRD with versioned change log",
     "Prioritized requirement list with acceptance criteria",
     "Success metrics and instrumentation plan"],
    ["Writing solution specs disguised as requirements",
     "Omitting non-goals, leaving scope unbounded",
     "No measurable success criteria — 'we'll know it when we see it'"],
    [("prd", "Product Requirements Document"), ("launch-criteria", "Launch Criteria")],
    ["% requirements with acceptance criteria", "Scope changes after sign-off"])

add("product", "requirements-analysis",
    "Requirements Analysis",
    "Elicit, analyze, specify, and validate requirements that are complete and testable.",
    "Turn vague needs into unambiguous, traceable, testable requirements so the team builds the right thing and can prove it later.",
    ["Functional vs non-functional requirement separation",
     "Elicitation techniques and requirement prioritization",
     "Ambiguity, completeness, and consistency analysis",
     "Traceability matrix from need to requirement to test",
     "Acceptance criteria authoring (Given/When/Then)"],
    ["Requirements specification (SRS) with IDs",
     "Requirements traceability matrix",
     "Acceptance criteria per requirement"],
    ["Ambiguous words ('fast', 'easy', 'secure') with no measure",
     "Mixing requirements with implementation detail",
     "No traceability — orphan requirements and orphan tests"],
    [("srs", "Requirements Specification"), ("traceability-matrix", "Traceability Matrix")],
    ["% requirements testable", "Requirement defect leakage to later phases"])

add("product", "proposal-creation",
    "Proposal Creation",
    "Craft persuasive, accurate proposals that win approval and set correct expectations.",
    "Convert an opportunity into a decision-ready proposal that states value, scope, cost, timeline, and risk honestly enough to fund and deliver.",
    ["Executive summary and value proposition",
     "Scope, deliverables, and explicit exclusions",
     "Pricing/effort estimate and commercial terms",
     "Timeline, milestones, and assumptions",
     "Risk, dependencies, and acceptance terms"],
    ["Proposal document ready for stakeholder/client review",
     "Scope statement with exclusions",
     "Estimate and timeline with assumptions"],
    ["Over-promising scope to win, then failing delivery",
     "Burying assumptions and exclusions in fine print",
     "Pricing without a defensible estimate behind it"],
    [("proposal", "Proposal"), ("sow", "Statement of Work")],
    ["Win rate", "Scope/cost variance vs proposal"])

add("product", "user-story-generation",
    "User Story Generation",
    "Write small, valuable, testable user stories with clear acceptance criteria.",
    "Decompose requirements into INVEST-compliant stories that a team can estimate, build, test, and demo independently.",
    ["INVEST-compliant story slicing",
     "Role-goal-benefit framing ('As a... I want... so that...')",
     "Acceptance criteria in Given/When/Then",
     "Vertical slicing and story splitting patterns",
     "Definition of Ready and Definition of Done"],
    ["Backlog of estimable, testable stories",
     "Acceptance criteria per story",
     "Definition of Ready / Done"],
    ["Horizontal slices (DB story, API story) with no user value",
     "Acceptance criteria that restate the title",
     "Epics masquerading as stories — too big to finish in a sprint"],
    [("user-story", "User Story"), ("acceptance-criteria", "Acceptance Criteria")],
    ["% stories meeting Definition of Ready", "Story carryover rate"])

add("product", "risk-analysis",
    "Risk Analysis",
    "Identify, assess, and plan responses to risks before they become incidents.",
    "Make uncertainty explicit and managed: surface what could go wrong, how bad and how likely, and what the team will do about it.",
    ["Risk identification (technical, schedule, resource, market, compliance)",
     "Qualitative and quantitative scoring (probability × impact)",
     "Risk response strategies (avoid, mitigate, transfer, accept)",
     "Risk register ownership and monitoring",
     "Assumption and dependency risk tracking"],
    ["Risk register with scores, owners, and responses",
     "Top-risk heat map",
     "Contingency and mitigation plans"],
    ["A risk register written once and never revisited",
     "Risks with no owner and no trigger condition",
     "Scoring theatre — numbers with no action attached"],
    [("risk-register", "Risk Register"), ("risk-matrix", "Risk Matrix")],
    ["% risks with active mitigation", "Risks that became issues unmanaged"])

add("product", "cost-estimation",
    "Cost Estimation",
    "Produce defensible effort and cost estimates with explicit ranges and assumptions.",
    "Give decision-makers an honest, range-based view of cost and effort, with the assumptions and uncertainty made visible rather than hidden in a single number.",
    ["Estimation techniques (analogous, parametric, bottom-up, three-point)",
     "Effort-to-cost conversion and total cost of ownership (TCO)",
     "Uncertainty ranges and confidence levels (PERT)",
     "Contingency and management reserve",
     "Cost drivers, assumptions, and exclusions"],
    ["Estimate with ranges, confidence, and assumptions",
     "Cost breakdown structure",
     "TCO model where relevant"],
    ["Single-point estimates presented as certainty",
     "Padding hidden in line items instead of explicit contingency",
     "Ignoring run/operate cost and counting only build cost"],
    [("estimate", "Cost Estimate"), ("tco-model", "TCO Model")],
    ["Estimate vs actual variance", "% estimates within stated range"])

add("product", "roadmap-planning",
    "Roadmap Planning",
    "Sequence outcomes over time, balancing value, dependencies, and capacity.",
    "Communicate where the product is going and why, as a living plan of outcomes (not a dated feature list) that survives contact with reality.",
    ["Outcome-based theming (now / next / later)",
     "Prioritization frameworks (RICE, WSJF, value vs effort)",
     "Dependency and capacity-aware sequencing",
     "Milestone and release alignment",
     "Stakeholder communication and roadmap versioning"],
    ["Outcome-oriented roadmap (now/next/later)",
     "Prioritized initiative list with rationale",
     "Dependency-aware sequence"],
    ["Date-locked feature factory roadmaps that mislead",
     "Prioritizing by loudest stakeholder rather than value/effort",
     "A roadmap that is never revisited as facts change"],
    [("roadmap", "Roadmap"), ("prioritization", "Prioritization Worksheet")],
    ["% roadmap items delivering stated outcome", "Roadmap churn rate"])


# ============================ ARCHITECTURE ============================

add("architecture", "design-document",
    "Design Document",
    "Author a technical design doc that explains the what, why, and trade-offs of a solution.",
    "Force clear thinking and enable review before code is written: capture context, goals, the chosen design, alternatives considered, and risks in one reviewable document.",
    ["Context, problem statement, and goals/non-goals",
     "Proposed design with diagrams (C4, sequence, data flow)",
     "Alternatives considered and why rejected",
     "Cross-cutting concerns (security, scaling, observability, cost)",
     "Rollout, migration, and testing strategy"],
    ["Reviewed design document (RFC/TDD)",
     "Architecture diagrams",
     "Decision record of the chosen approach"],
    ["Describing the solution without the alternatives or trade-offs",
     "Diagrams that don't match the prose",
     "No non-goals, so review scope creeps endlessly"],
    [("design-doc", "Technical Design Document"), ("rfc", "RFC")],
    ["Design review turnaround time", "Defects traced to missing design review"])

add("architecture", "architecture-review",
    "Architecture Review",
    "Systematically evaluate an architecture against quality attributes and risks.",
    "Provide an objective, repeatable assessment of whether an architecture meets its quality attributes (scalability, security, maintainability) and surface risks early.",
    ["Quality-attribute scenario evaluation (ATAM-style)",
     "Risk, sensitivity, and trade-off point identification",
     "Fitness-function and constraint checking",
     "Tech-debt and coupling assessment",
     "Compliance with reference architecture and standards"],
    ["Architecture review report with findings and severity",
     "Risk and trade-off log",
     "Prioritized remediation recommendations"],
    ["Opinion-based review with no quality-attribute scenarios",
     "Reviewing the diagram, not the running system's reality",
     "Findings with no severity, owner, or remediation"],
    [("review-report", "Architecture Review Report"), ("qa-scenarios", "Quality-Attribute Scenarios")],
    ["High-severity findings closed", "Re-review pass rate"])

add("architecture", "frontend-architecture",
    "Frontend Architecture",
    "Define the structure, boundaries, and standards for a maintainable frontend.",
    "Establish how the frontend is organized — rendering strategy, module boundaries, state, data fetching, and build — so teams move fast without creating a tangle.",
    ["Rendering strategy (SPA, SSR, SSG, ISR, islands) selection",
     "Module/feature boundaries and folder architecture",
     "State and data-fetching architecture",
     "Design-system and component-library integration",
     "Build, bundling, code-splitting, and performance budgets"],
    ["Frontend architecture document",
     "Module boundary and dependency rules",
     "Rendering and data-fetching decision record"],
    ["Choosing SSR/SPA by trend rather than requirements",
     "Global mutable state as the default for everything",
     "No performance budget — bundle size grows unchecked"],
    [("fe-architecture", "Frontend Architecture"), ("rendering-decision", "Rendering Strategy Decision")],
    ["Bundle size vs budget", "Build time", "Lighthouse/Core Web Vitals"])

add("architecture", "backend-architecture",
    "Backend Architecture",
    "Define service boundaries, data ownership, and communication for the backend.",
    "Decide how backend responsibilities are partitioned into services, who owns which data, and how components communicate — synchronously and asynchronously.",
    ["Service boundary and responsibility definition",
     "Data ownership and consistency model (per-service data)",
     "Sync vs async communication and contracts",
     "Cross-cutting concerns (auth, logging, idempotency, retries)",
     "Layering, modularity, and dependency direction"],
    ["Backend architecture document with service map",
     "Data ownership and consistency decisions",
     "Communication and contract standards"],
    ["Distributed monolith — services that can't deploy independently",
     "Shared database across service boundaries",
     "Synchronous chains that fail together under load"],
    [("be-architecture", "Backend Architecture"), ("service-map", "Service Map")],
    ["Independent deployability of services", "Cross-service coupling incidents"])

add("architecture", "api-design",
    "API Design",
    "Design clear, consistent, evolvable APIs that are a pleasure to consume.",
    "Treat the API as a product: design resources, contracts, errors, and versioning so consumers can integrate confidently and the API can evolve without breaking them.",
    ["Resource modeling and REST/GraphQL/gRPC style selection",
     "Naming, pagination, filtering, and consistency conventions",
     "Error model, status codes, and idempotency",
     "Versioning and backward-compatibility strategy",
     "AuthN/Z, rate limiting, and contract documentation (OpenAPI)"],
    ["API design spec / OpenAPI definition",
     "Error and versioning conventions",
     "Consumer-facing API documentation"],
    ["Leaking internal data models straight to the wire",
     "Breaking changes without versioning or deprecation policy",
     "Inconsistent naming/errors across endpoints"],
    [("api-spec", "API Design Spec"), ("openapi", "OpenAPI Skeleton")],
    ["Breaking-change incidents", "Time-to-first-successful-call for new consumers"])

add("architecture", "database-design",
    "Database Design",
    "Model data for correctness, performance, and evolution.",
    "Design a data model that captures the domain accurately, performs under real access patterns, and can evolve safely with migrations.",
    ["Conceptual / logical / physical modeling",
     "Normalization vs deliberate denormalization",
     "Indexing and access-pattern-driven design",
     "Constraints, integrity, and transactions",
     "Migration and schema-evolution strategy"],
    ["ERD and schema definition (DDL)",
     "Indexing and access-pattern notes",
     "Migration plan"],
    ["Modeling tables before knowing the query patterns",
     "No constraints — relying on app code for integrity",
     "Big-bang migrations with no rollback"],
    [("data-model", "Data Model & ERD"), ("migration-plan", "Migration Plan")],
    ["Query p95 vs target", "Migration rollback readiness"])

add("architecture", "security-architecture",
    "Security Architecture",
    "Design defense-in-depth security into the system from the start.",
    "Bake security into the architecture — trust boundaries, identity, data protection, and controls — so security is structural rather than bolted on later.",
    ["Trust boundaries and zero-trust segmentation",
     "Identity, authN/authZ, and secrets architecture",
     "Data protection (encryption in transit/at rest, key management)",
     "Threat modeling integration (STRIDE) and security controls",
     "Compliance mapping and security logging/audit"],
    ["Security architecture document with trust boundaries",
     "Control catalogue mapped to threats",
     "Data-protection and key-management plan"],
    ["Perimeter-only security with a soft interior",
     "Secrets in code/config instead of a managed store",
     "Security designed after the architecture is frozen"],
    [("security-arch", "Security Architecture"), ("control-catalogue", "Control Catalogue")],
    ["Controls mapped to threats", "Findings from pen test vs design"])

add("architecture", "scalability-planning",
    "Scalability Planning",
    "Plan how the system grows with load without surprise cost or failure.",
    "Anticipate growth: identify bottlenecks, define scaling strategies and limits, and set capacity targets before load — not during an incident.",
    ["Load modeling and capacity planning",
     "Horizontal vs vertical scaling and statelessness",
     "Bottleneck and single-point-of-failure analysis",
     "Caching, partitioning/sharding, and queueing strategies",
     "Autoscaling policies and load/soak testing"],
    ["Scalability plan with capacity targets",
     "Bottleneck and SPOF inventory",
     "Scaling and autoscaling strategy"],
    ["Premature optimization for scale you'll never reach",
     "Stateful services that block horizontal scaling",
     "No load testing to validate the assumptions"],
    [("scalability-plan", "Scalability Plan"), ("capacity-model", "Capacity Model")],
    ["Headroom at peak", "Cost per unit of load"])

add("architecture", "event-driven-architecture",
    "Event-Driven Architecture",
    "Design loosely-coupled systems around events, with reliable delivery semantics.",
    "Decouple producers and consumers through events while making delivery, ordering, and consistency guarantees explicit and handled.",
    ["Event modeling, schemas, and a schema registry",
     "Delivery semantics (at-least/exactly-once) and idempotency",
     "Ordering, partitioning, and the outbox/saga patterns",
     "Choreography vs orchestration trade-offs",
     "Dead-letter handling, replay, and observability"],
    ["Event catalogue with versioned schemas",
     "Delivery-semantics and idempotency decisions",
     "Saga/outbox design for consistency"],
    ["Events as disguised RPC (tight coupling, no autonomy)",
     "No idempotency — duplicates corrupt state",
     "Unversioned event schemas that break consumers"],
    [("event-catalogue", "Event Catalogue"), ("saga-design", "Saga Design")],
    ["Consumer lag", "Duplicate/poison-message rate"])

add("architecture", "multi-tenant-architecture",
    "Multi-Tenant Architecture",
    "Isolate, scale, and operate many tenants safely on shared infrastructure.",
    "Decide the tenancy model and isolation guarantees so tenants share efficiency without sharing data, blast radius, or noisy-neighbor pain.",
    ["Isolation model (silo / pool / bridge) selection",
     "Tenant data isolation and the row/schema/db trade-off",
     "Tenant context propagation and request routing",
     "Per-tenant limits, metering, and noisy-neighbor control",
     "Tenant lifecycle (onboard, offboard, data export/delete)"],
    ["Tenancy model decision with isolation guarantees",
     "Tenant data-isolation design",
     "Tenant lifecycle and metering plan"],
    ["A single missing tenant filter leaking cross-tenant data",
     "One-size isolation when tiers need different guarantees",
     "No noisy-neighbor controls — one tenant starves the rest"],
    [("tenancy-model", "Tenancy Model"), ("isolation-design", "Isolation Design")],
    ["Cross-tenant isolation test pass rate", "Cost per tenant"])

add("architecture", "domain-driven-design",
    "Domain-Driven Design",
    "Model complex domains with bounded contexts and a shared ubiquitous language.",
    "Align software structure with the business domain: discover bounded contexts, define a ubiquitous language, and model aggregates that protect invariants.",
    ["Ubiquitous language and domain glossary",
     "Bounded contexts and a context map",
     "Aggregates, entities, value objects, and invariants",
     "Domain events and application/domain layering",
     "Strategic vs tactical DDD and anti-corruption layers"],
    ["Context map with relationships",
     "Ubiquitous-language glossary",
     "Aggregate and domain-event model"],
    ["Anemic domain models — logic leaks into services",
     "One giant model instead of bounded contexts",
     "Sharing models across contexts without an anti-corruption layer"],
    [("context-map", "Context Map"), ("ubiquitous-language", "Ubiquitous Language Glossary")],
    ["Context boundary stability", "Domain logic centralization"])

add("architecture", "microservices-governance",
    "Microservices Governance",
    "Set the standards that keep many services consistent, observable, and safe.",
    "Provide the guardrails — service standards, ownership, versioning, and a paved road — that let many teams run microservices without chaos.",
    ["Service ownership, catalog, and a paved-road platform",
     "API/contract versioning and compatibility policy",
     "Cross-cutting standards (logging, tracing, health, security)",
     "Service maturity/readiness checklists",
     "Decentralized data and inter-service dependency rules"],
    ["Service standards and golden-path templates",
     "Service catalog with ownership",
     "Versioning and readiness policy"],
    ["Governance as a gatekeeping committee that slows everyone",
     "No standards — every service reinvents logging/auth",
     "A service catalog nobody keeps up to date"],
    [("service-standards", "Service Standards"), ("readiness-checklist", "Service Readiness Checklist")],
    ["% services on the paved road", "Standards compliance score"])


# ============================ FRONTEND ============================

add("frontend", "ui-ux-design",
    "UI/UX Design",
    "Design usable, accessible, consistent interfaces grounded in user needs.",
    "Turn user needs into interfaces that are intuitive, accessible, and consistent — validated with users rather than assumed.",
    ["User research, personas, and journey mapping",
     "Information architecture and interaction design",
     "Wireframes, prototypes, and usability testing",
     "Visual hierarchy, consistency, and design heuristics",
     "Accessibility-by-design (WCAG) and responsive layout"],
    ["Wireframes/prototypes for key flows",
     "Usability test findings",
     "Annotated UI specs for handoff"],
    ["Designing for stakeholders' taste, not user evidence",
     "Skipping usability testing until after build",
     "Inconsistent patterns across screens"],
    [("ux-spec", "UX Spec"), ("usability-test-plan", "Usability Test Plan")],
    ["Task success rate", "Time-on-task", "SUS score"])

add("frontend", "component-design",
    "Component Design",
    "Design reusable, composable, well-documented UI components.",
    "Build a component as a small product: a clear API, predictable states, accessibility, and documentation so it's reused rather than re-created.",
    ["Component API (props/events/slots) and composition model",
     "State, variant, and interaction matrix",
     "Accessibility (roles, keyboard, focus, ARIA)",
     "Theming, tokens, and style encapsulation",
     "Stories, docs, and visual-regression coverage"],
    ["Component spec with API and states",
     "Accessibility and interaction checklist",
     "Stories/docs and tests"],
    ["Over-configurable components with 30 boolean props",
     "Components that hard-code spacing/colors instead of tokens",
     "Skipping keyboard/focus handling"],
    [("component-spec", "Component Spec"), ("component-api", "Component API")],
    ["Reuse rate", "A11y violations per component"])

add("frontend", "state-management",
    "State Management",
    "Choose and structure client state for predictability and performance.",
    "Decide what state exists, where it lives (server, URL, local, global), and how it changes — avoiding the global-store-for-everything trap.",
    ["State categorization (server, URL, form, UI, global)",
     "Server-state caching (query libraries) vs client state",
     "Store design, selectors, and normalization",
     "Derived state and avoiding redundant sources of truth",
     "Performance (re-render control, memoization, splitting)"],
    ["State architecture decision record",
     "State ownership map",
     "Caching/invalidation strategy"],
    ["Putting server data in a global store and hand-syncing it",
     "One mega-store causing app-wide re-renders",
     "Duplicating the same truth in multiple places"],
    [("state-architecture", "State Architecture"), ("state-map", "State Ownership Map")],
    ["Unnecessary re-renders", "Stale-data bugs"])

add("frontend", "frontend-testing",
    "Frontend Testing",
    "Build a layered frontend test strategy that catches regressions cheaply.",
    "Define what to test and at which level — unit, component, integration, e2e, visual — to maximize confidence per minute of test runtime.",
    ["Test pyramid for the frontend and what each layer owns",
     "Component testing with user-centric queries",
     "Mocking the network at the boundary and test-data strategy",
     "Visual-regression and accessibility testing",
     "Flake control, determinism, and CI integration"],
    ["Frontend test strategy",
     "Coverage targets per layer",
     "Flake and CI policy"],
    ["Testing implementation details that break on refactor",
     "An inverted pyramid — slow e2e for everything",
     "Tolerating flaky tests instead of fixing them"],
    [("fe-test-strategy", "Frontend Test Strategy"), ("test-plan", "Test Plan")],
    ["Critical-path coverage", "Flake rate", "Test runtime"])

add("frontend", "frontend-optimization",
    "Frontend Optimization",
    "Improve load and runtime performance against measured budgets.",
    "Make the app fast for real users by measuring Core Web Vitals, finding the actual bottlenecks, and optimizing against explicit budgets.",
    ["Core Web Vitals (LCP, INP, CLS) measurement and budgets",
     "Bundle analysis, code-splitting, and tree-shaking",
     "Image/font optimization and resource hints",
     "Rendering/runtime perf (virtualization, memoization)",
     "Caching, CDN, and network optimization"],
    ["Performance budget and baseline",
     "Optimization backlog ranked by impact",
     "Before/after measurements"],
    ["Optimizing without measuring first",
     "Micro-optimizing JS while shipping a 4 MB hero image",
     "No budget — gains regress silently next release"],
    [("perf-budget", "Performance Budget"), ("optimization-plan", "Optimization Plan")],
    ["LCP / INP / CLS", "Bundle size", "Time to interactive"])

add("frontend", "accessibility-review",
    "Accessibility Review",
    "Audit and remediate against WCAG so the product works for everyone.",
    "Make the product usable by people with disabilities and compliant with WCAG/legal requirements through systematic audit and remediation.",
    ["WCAG 2.2 AA conformance auditing",
     "Keyboard, focus order, and screen-reader testing",
     "Color contrast, target size, and motion preferences",
     "Semantic HTML and ARIA correctness",
     "Automated + manual + assistive-tech testing"],
    ["Accessibility audit report (issues by WCAG criterion)",
     "Prioritized remediation backlog",
     "Conformance statement (VPAT-style)"],
    ["Relying only on automated scanners (catch ~30%)",
     "ARIA-over-HTML — reinventing native semantics badly",
     "Treating a11y as a one-off audit, not a standard"],
    [("a11y-audit", "Accessibility Audit"), ("vpat", "Conformance Statement")],
    ["WCAG criteria passed", "Critical a11y issues open"])

add("frontend", "design-system",
    "Design System",
    "Build a shared system of tokens, components, and guidelines for consistency at scale.",
    "Create a single source of truth — design tokens, components, patterns, and usage guidance — so product teams build consistent UI faster.",
    ["Design tokens (color, type, spacing, motion) and theming",
     "Component library architecture and versioning",
     "Documentation, usage guidelines, and governance",
     "Design–code parity and contribution model",
     "Adoption, deprecation, and release process"],
    ["Token set and theme definitions",
     "Versioned, documented component library",
     "Governance and contribution guide"],
    ["Components without tokens — divergence creeps back in",
     "No governance — forks and one-off variants proliferate",
     "Design and code drifting out of parity"],
    [("design-tokens", "Design Tokens"), ("ds-governance", "Design System Governance")],
    ["Adoption rate across teams", "Design–code parity"])


# ============================ BACKEND ============================

add("backend", "service-design",
    "Service Design",
    "Design a single backend service with clear contracts, boundaries, and operations.",
    "Specify one service end-to-end: its responsibility, API, data, dependencies, failure modes, and operational shape — so it's reliable and ownable.",
    ["Single-responsibility boundary and public contract",
     "Data ownership and persistence choice",
     "Dependency, timeout, retry, and circuit-breaker policy",
     "Idempotency, concurrency, and consistency handling",
     "Observability, health checks, and SLOs"],
    ["Service spec (contract, data, dependencies)",
     "Failure-mode and resilience plan",
     "SLOs and observability plan"],
    ["A service that owns no data and just forwards calls",
     "No timeouts/retries — one slow dependency cascades",
     "No health checks or SLOs to operate against"],
    [("service-spec", "Service Spec"), ("slo-doc", "SLO Definition")],
    ["SLO attainment", "Error budget burn"])

add("backend", "authentication-design",
    "Authentication Design",
    "Design secure authentication and session/token handling.",
    "Choose and design how users and services prove identity — protocols, tokens, sessions, MFA — without rolling fragile crypto yourself.",
    ["AuthN protocol selection (OIDC/OAuth2, SAML, passkeys)",
     "Token vs session design and lifetimes/rotation",
     "MFA, passwordless, and account-recovery flows",
     "Credential storage (hashing) and secret handling",
     "Federation, SSO, and service-to-service auth"],
    ["Authentication design with chosen protocol",
     "Token/session lifecycle and rotation policy",
     "MFA and recovery flow design"],
    ["Rolling your own crypto/token format",
     "Long-lived tokens with no rotation or revocation",
     "Storing passwords with fast or reversible hashing"],
    [("authn-design", "Authentication Design"), ("token-policy", "Token & Session Policy")],
    ["Account-takeover incidents", "MFA adoption"])

add("backend", "database-optimization",
    "Database Optimization",
    "Diagnose and fix database performance against real workloads.",
    "Find and remove the actual database bottlenecks — slow queries, missing indexes, lock contention — using evidence from query plans and metrics.",
    ["Slow-query identification and EXPLAIN plan analysis",
     "Index design, covering indexes, and index hygiene",
     "Query rewriting and N+1 elimination",
     "Connection pooling, caching, and read replicas",
     "Partitioning, vacuum/stats, and configuration tuning"],
    ["Optimization report with before/after metrics",
     "Index and query change set",
     "Monitoring for regression"],
    ["Adding indexes blindly without checking plans",
     "Optimizing queries that aren't the bottleneck",
     "Fixing symptoms in app code instead of the query/schema"],
    [("db-tuning", "DB Tuning Plan"), ("query-analysis", "Query Analysis")],
    ["Query p95/p99", "Index hit ratio", "Lock wait time"])

add("backend", "caching-strategy",
    "Caching Strategy",
    "Add caching that speeds things up without serving wrong data.",
    "Decide what to cache, where, and how it's invalidated so you gain performance without stale-data or thundering-herd bugs.",
    ["Cache layer selection (client, CDN, app, db) and topology",
     "Cache patterns (cache-aside, read/write-through, write-behind)",
     "TTL, invalidation, and consistency trade-offs",
     "Key design, stampede protection, and warming",
     "Hit-ratio monitoring and eviction policy"],
    ["Caching strategy per data type",
     "Invalidation and consistency plan",
     "Cache-key and TTL conventions"],
    ["Caching with no invalidation plan — permanent stale data",
     "Caching highly volatile or per-user-sensitive data wrongly",
     "No stampede protection — cache miss melts the origin"],
    [("caching-strategy", "Caching Strategy"), ("invalidation-plan", "Invalidation Plan")],
    ["Cache hit ratio", "Origin load reduction", "Stale-read incidents"])

add("backend", "background-jobs",
    "Background Jobs",
    "Design reliable async job processing with retries, idempotency, and visibility.",
    "Move work off the request path reliably: choose a queue, design jobs to be idempotent and retryable, and make failures visible and recoverable.",
    ["Queue/broker selection and topology",
     "Job idempotency, retries, and backoff",
     "Dead-letter queues and poison-message handling",
     "Scheduling, prioritization, and concurrency limits",
     "Observability, alerting, and backpressure"],
    ["Job processing design",
     "Retry/DLQ and idempotency policy",
     "Monitoring and alerting plan"],
    ["Non-idempotent jobs that double-charge on retry",
     "No dead-letter queue — failures vanish silently",
     "Unbounded concurrency overwhelming downstreams"],
    [("job-design", "Background Job Design"), ("queue-topology", "Queue Topology")],
    ["Job success rate", "Queue depth/age", "DLQ rate"])

add("backend", "api-contract-design",
    "API Contract Design",
    "Define and govern machine-readable contracts as the source of truth.",
    "Make the contract — OpenAPI/Protobuf/GraphQL schema — the authoritative interface, enabling codegen, mocking, and automated compatibility checks.",
    ["Contract-first authoring (OpenAPI / Protobuf / GraphQL SDL)",
     "Schema validation and codegen for clients/servers",
     "Backward/forward compatibility and breaking-change detection",
     "Contract testing (consumer-driven) and mocking",
     "Versioning, deprecation, and changelog discipline"],
    ["Versioned contract artifact in the registry",
     "Compatibility/linting CI checks",
     "Consumer-driven contract tests"],
    ["Code-first with the contract reverse-engineered after",
     "Merging breaking changes with no automated detection",
     "Contracts that drift from the running implementation"],
    [("contract-spec", "API Contract"), ("compat-policy", "Compatibility Policy")],
    ["Breaking changes caught in CI", "Contract-test coverage"])

add("backend", "file-storage-design",
    "File Storage Design",
    "Design secure, scalable storage for files and media.",
    "Decide how files are stored, served, secured, and lifecycle-managed — object store, signed access, processing — without overloading the database or app.",
    ["Storage backend selection (object store, CDN, tiers)",
     "Upload/download flow with pre-signed URLs",
     "Access control, encryption, and virus scanning",
     "Media processing (resize/transcode) pipeline",
     "Lifecycle, retention, versioning, and cost tiering"],
    ["File storage design",
     "Access-control and signed-URL flow",
     "Lifecycle/retention policy"],
    ["Storing large blobs in the relational database",
     "Public buckets / unsigned access to private files",
     "No retention policy — storage and cost grow forever"],
    [("storage-design", "File Storage Design"), ("upload-flow", "Upload/Download Flow")],
    ["Storage cost per GB", "Upload success rate", "Serve latency"])

add("backend", "search-architecture",
    "Search Architecture",
    "Design relevant, fast, scalable search over your data.",
    "Build search that returns relevant results quickly: choose the engine, design indexing and relevance, and keep the index in sync with the source.",
    ["Search engine selection (full-text, vector, hybrid)",
     "Index modeling, analyzers, and mapping",
     "Relevance tuning, ranking, and faceting",
     "Indexing pipeline and source-of-truth sync",
     "Query performance, pagination, and observability"],
    ["Search architecture and index design",
     "Relevance/ranking strategy",
     "Indexing/sync pipeline design"],
    ["Using SQL LIKE for real search workloads",
     "Index drift — search results don't match the source",
     "Tuning relevance with no evaluation set to measure it"],
    [("search-design", "Search Architecture"), ("relevance-plan", "Relevance Tuning Plan")],
    ["Search latency p95", "Relevance (nDCG/CTR)", "Index freshness lag"])


# ============================ AI & DATA ============================

add("ai", "ai-agent-design",
    "AI Agent Design",
    "Design reliable LLM agents with clear tools, control flow, and guardrails.",
    "Specify an agent's job, tools, control loop, memory, and stop conditions so it accomplishes tasks reliably and safely — not just impressively in a demo.",
    ["Task scoping, success criteria, and stop conditions",
     "Tool/function definitions and permissioning",
     "Control flow (single-shot, ReAct, planner-executor, multi-agent)",
     "Memory, context management, and state",
     "Guardrails, human-in-the-loop, and failure handling"],
    ["Agent design spec (goal, tools, loop, limits)",
     "Tool contract definitions",
     "Guardrail and HITL plan"],
    ["Giving an agent powerful tools with no permission scoping",
     "No stop conditions — runaway loops and cost",
     "Demo-driven design with no eval of real task success"],
    [("agent-spec", "Agent Design Spec"), ("tool-contract", "Tool Contract")],
    ["Task success rate", "Cost/latency per task", "Intervention rate"])

add("ai", "rag-architecture",
    "RAG Architecture",
    "Design retrieval-augmented generation that is accurate and grounded.",
    "Ground LLM answers in your data: design chunking, embedding, retrieval, and prompting so responses are accurate, cited, and current.",
    ["Ingestion, chunking, and metadata strategy",
     "Embedding model selection and vector store design",
     "Retrieval (dense/sparse/hybrid), re-ranking, and filtering",
     "Context assembly, prompting, and citation",
     "Freshness, evaluation, and hallucination control"],
    ["RAG architecture document",
     "Chunking/embedding/retrieval design",
     "Evaluation harness and metrics"],
    ["Naive fixed-size chunking that splits meaning",
     "No re-ranking — irrelevant context drowns the answer",
     "No retrieval/grounding evaluation"],
    [("rag-design", "RAG Architecture"), ("eval-harness", "RAG Evaluation Harness")],
    ["Answer faithfulness", "Retrieval precision/recall", "Citation rate"])

add("ai", "prompt-engineering",
    "Prompt Engineering",
    "Design, version, and test prompts that are reliable and maintainable.",
    "Treat prompts as engineered, versioned, tested artifacts — structured, evaluated, and robust to edge cases — rather than ad-hoc strings.",
    ["Prompt structure (role, instructions, context, examples, format)",
     "Few-shot, chain-of-thought, and decomposition techniques",
     "Output formatting (JSON/schema) and parsing robustness",
     "Prompt versioning, testing, and regression evals",
     "Injection resistance and failure handling"],
    ["Versioned prompt library with eval results",
     "Prompt spec per task (inputs/outputs/format)",
     "Regression eval set"],
    ["Untracked prompt strings edited live in production",
     "No eval set — 'it looked better' tuning",
     "Trusting model output format without validation"],
    [("prompt-spec", "Prompt Spec"), ("eval-set", "Prompt Eval Set")],
    ["Eval pass rate", "Output-format validity", "Regression catch rate"])

add("ai", "model-selection",
    "Model Selection",
    "Choose the right model for the task on quality, cost, latency, and risk.",
    "Make an evidence-based model choice: define requirements, benchmark candidates on your own data, and decide on quality, cost, latency, and constraints.",
    ["Requirement definition (quality, latency, cost, context, modality)",
     "Candidate shortlist (frontier vs small vs open vs fine-tuned)",
     "Task-specific benchmarking on representative data",
     "Cost/latency modeling at expected volume",
     "Data-residency, privacy, and licensing constraints"],
    ["Model selection decision record with benchmark data",
     "Cost/latency model at projected volume",
     "Fallback/routing strategy"],
    ["Picking by leaderboard rank, not your task evals",
     "Ignoring cost/latency at production scale",
     "No fallback when the chosen model is down or degraded"],
    [("model-decision", "Model Selection Decision"), ("benchmark-plan", "Benchmark Plan")],
    ["Quality on task evals", "Cost per 1k requests", "p95 latency"])

add("ai", "ai-evaluation",
    "AI Evaluation",
    "Build evaluation harnesses that measure AI quality objectively and repeatably.",
    "Replace vibes with measurement: build datasets, metrics, and harnesses (including LLM-as-judge) that gate releases and catch regressions.",
    ["Eval dataset construction and golden sets",
     "Metric selection (task metrics, faithfulness, safety)",
     "LLM-as-judge design and human eval calibration",
     "Offline vs online eval and A/B testing",
     "Regression gating and continuous evaluation in CI"],
    ["Evaluation harness with datasets and metrics",
     "Baseline scores and release gates",
     "Continuous-eval integration"],
    ["LLM-as-judge with no human calibration",
     "Evaluating on data the model trained/was tuned on (leakage)",
     "One-off eval rather than a regression gate"],
    [("eval-plan", "AI Evaluation Plan"), ("golden-set", "Golden Dataset")],
    ["Eval coverage of use cases", "Regression catch rate", "Judge–human agreement"])

add("ai", "llmops",
    "LLMOps",
    "Operate LLM applications in production with versioning, monitoring, and cost control.",
    "Bring engineering discipline to running LLM apps: version prompts/models, manage deployments, monitor quality and cost, and respond to drift.",
    ["Prompt/model versioning and deployment (canary, rollback)",
     "Observability (traces, tokens, latency, quality signals)",
     "Cost monitoring, budgets, and caching/routing",
     "Drift, feedback loops, and continuous evaluation",
     "Guardrail, rate-limit, and incident operations"],
    ["LLMOps runbook and deployment process",
     "Monitoring and cost dashboards",
     "Drift and incident response plan"],
    ["Shipping prompt/model changes with no versioning or rollback",
     "No cost guardrails — runaway token spend",
     "No production quality monitoring (drift goes unnoticed)"],
    [("llmops-runbook", "LLMOps Runbook"), ("monitoring-plan", "LLM Monitoring Plan")],
    ["Cost per request", "Quality drift", "Deployment rollback time"])

add("ai", "vector-database-design",
    "Vector Database Design",
    "Design vector storage and indexing for fast, accurate similarity search.",
    "Choose and configure a vector store: index type, distance metric, metadata filtering, and scaling — balancing recall, latency, and cost.",
    ["Vector store selection and deployment model",
     "Index type (HNSW, IVF, etc.) and parameter tuning",
     "Distance metric and embedding dimensionality",
     "Metadata filtering and hybrid search",
     "Recall/latency trade-offs, sharding, and scaling"],
    ["Vector DB design and configuration",
     "Index/parameter tuning plan",
     "Scaling and cost model"],
    ["Default index params without recall/latency testing",
     "Mismatched distance metric vs embedding model",
     "Ignoring metadata filtering and re-indexing cost"],
    [("vectordb-design", "Vector DB Design"), ("index-tuning", "Index Tuning Plan")],
    ["Recall@k", "Query latency p95", "Cost per million vectors"])

add("ai", "ai-monitoring",
    "AI Monitoring",
    "Monitor AI systems for quality, drift, safety, and cost in production.",
    "Detect when an AI system degrades — quality drift, data drift, safety violations, cost spikes — before users or the business are harmed.",
    ["Quality and output-drift monitoring",
     "Input/data-drift and distribution shift detection",
     "Safety, toxicity, and policy-violation monitoring",
     "Cost, latency, and token-usage tracking",
     "Feedback capture, alerting, and dashboards"],
    ["AI monitoring plan and dashboards",
     "Drift and safety alert thresholds",
     "Feedback-to-improvement loop"],
    ["Monitoring infra metrics but not output quality",
     "No drift detection — silent degradation over time",
     "Alerts with no thresholds tied to user impact"],
    [("ai-monitoring-plan", "AI Monitoring Plan"), ("drift-alerts", "Drift Alert Config")],
    ["Drift detection lead time", "Safety violation rate", "Cost variance"])

add("ai", "model-finetuning",
    "Model Fine-Tuning",
    "Decide when and how to fine-tune, with data, method, and evaluation discipline.",
    "Determine whether fine-tuning beats prompting/RAG, then do it rigorously: curate data, pick a method, train, and evaluate against a baseline.",
    ["Fine-tune vs prompt vs RAG decision",
     "Dataset curation, labeling, and quality/bias checks",
     "Method selection (full, LoRA/PEFT, instruction, DPO/RLHF)",
     "Training setup, hyperparameters, and compute",
     "Evaluation vs baseline and regression/safety checks"],
    ["Fine-tuning decision and plan",
     "Curated, documented training dataset",
     "Eval results vs baseline"],
    ["Fine-tuning when prompting/RAG would suffice",
     "Training on small, biased, or leaky data",
     "No baseline comparison to prove the gain"],
    [("finetune-plan", "Fine-Tuning Plan"), ("dataset-card", "Dataset Card")],
    ["Task quality lift vs baseline", "Cost vs alternative", "Regression rate"])

add("ai", "data-pipeline-design",
    "Data Pipeline Design",
    "Design reliable ingestion and transformation pipelines that move data correctly and observably.",
    "Move data from sources to destinations correctly, on time, and observably. Design the ingestion, validation, transformation, and loading stages — batch or streaming — so downstream consumers (analytics, search, RAG, ML) receive trustworthy, fresh data without silent corruption.",
    ["Source/sink inventory and the batch vs streaming decision",
     "Pipeline stages: ingest/extract, validate, transform, load (ETL/ELT)",
     "Schema management, source contracts, and schema-drift handling",
     "Data-quality checks, deduplication, and idempotent/exactly-once processing",
     "Orchestration, scheduling, dependencies, and backfills",
     "Lineage, freshness SLAs, observability, and failure recovery/replay"],
    ["Data pipeline design (stages, schemas, and a data-flow diagram)",
     "Data-quality and validation rules",
     "Orchestration, scheduling, and backfill plan"],
    ["Pipelines with no data-quality checks that propagate corruption downstream",
     "Non-idempotent loads that double-count on retry or backfill",
     "No schema-drift handling, so an upstream change breaks the pipeline silently"],
    [("pipeline-design", "Data Pipeline Design"), ("data-quality-rules", "Data Quality Rules")],
    ["Data freshness / end-to-end latency", "Data-quality pass rate",
     "Pipeline success rate", "Backfill / replay time"])

add("ai", "guardrails-design",
    "Guardrails Design",
    "Design input/output safety controls for AI systems.",
    "Keep AI systems safe and on-policy: validate inputs, filter outputs, prevent injection and data leakage, and define what to do when a guardrail trips.",
    ["Input validation, moderation, and prompt-injection defense",
     "Output filtering (toxicity, PII, policy, format)",
     "Topic/scope restriction and refusal design",
     "Sensitive-data leakage prevention",
     "Guardrail failure handling, logging, and HITL escalation"],
    ["Guardrail policy and control set",
     "Input/output validation design",
     "Violation handling and escalation plan"],
    ["Relying on the model's own judgment as the only guardrail",
     "Output-only filtering, ignoring injection at the input",
     "Silent guardrail failures with no logging/alerting"],
    [("guardrail-policy", "Guardrail Policy"), ("violation-handling", "Violation Handling Plan")],
    ["Violation catch rate", "False-positive (over-refusal) rate", "Injection block rate"])


# ============================ TESTING & QUALITY ============================

add("testing", "testing-strategy",
    "Testing Strategy",
    "Define the overall test approach: levels, coverage, environments, and ownership.",
    "Set the testing philosophy for a product: what to test at each level, coverage targets, environments, data, and who owns what — so quality is engineered, not hoped for.",
    ["Test pyramid/trophy and level responsibilities",
     "Coverage targets and risk-based prioritization",
     "Test environments and data management",
     "Automation vs manual and exploratory testing",
     "Quality gates, ownership, and shift-left practices"],
    ["Test strategy document",
     "Coverage targets per level",
     "Quality gate and ownership model"],
    ["Coverage-percentage worship over meaningful tests",
     "Inverted pyramid — slow, brittle, expensive suites",
     "No environment/data strategy — flaky, unrepeatable runs"],
    [("test-strategy", "Test Strategy"), ("quality-gates", "Quality Gates")],
    ["Escaped-defect rate", "Suite runtime", "Flake rate"])

add("testing", "unit-testing",
    "Unit Testing",
    "Write fast, focused, maintainable unit tests with good design.",
    "Establish how to write unit tests that document behavior, run fast, and survive refactoring — testing behavior, not implementation.",
    ["Test structure (AAA), naming, and behavior focus",
     "Test doubles (mock/stub/fake/spy) and when to use each",
     "Boundary, equivalence, and property-based testing",
     "Determinism, isolation, and speed",
     "Coverage interpretation and mutation testing"],
    ["Unit test conventions and examples",
     "Test-double guidelines",
     "Coverage/mutation targets"],
    ["Testing private internals — brittle on refactor",
     "Over-mocking until tests assert the mocks, not behavior",
     "Non-deterministic tests (time, randomness, ordering)"],
    [("unit-test-guide", "Unit Test Guidelines"), ("test-case", "Test Case")],
    ["Mutation score", "Test runtime", "Flake rate"])

add("testing", "integration-testing",
    "Integration Testing",
    "Verify components work together across real boundaries.",
    "Test the seams — services, databases, queues, third parties — where unit tests can't reach, using realistic dependencies and data.",
    ["Integration scope and boundary selection",
     "Realistic dependencies (testcontainers, sandboxes)",
     "Contract and API integration testing",
     "Test data setup/teardown and isolation",
     "Failure-mode and resilience testing"],
    ["Integration test plan and harness",
     "Environment/data setup approach",
     "Boundary coverage map"],
    ["Mocking the very integration you meant to test",
     "Shared mutable test data causing cross-test flake",
     "Only happy-path integration, no failure injection"],
    [("integration-plan", "Integration Test Plan"), ("test-harness", "Test Harness")],
    ["Boundary coverage", "Integration defect escape rate"])

add("testing", "performance-testing",
    "Performance Testing",
    "Validate the system meets performance and scalability targets under load.",
    "Prove the system performs under realistic and peak load: define targets, model load, run tests, and find bottlenecks before users do.",
    ["Workload modeling and performance requirements",
     "Test types (load, stress, soak, spike, capacity)",
     "Tooling, scripting, and realistic data",
     "Bottleneck analysis and profiling",
     "Baselining, regression, and CI integration"],
    ["Performance test plan with targets",
     "Test scripts and workload model",
     "Results report with bottlenecks"],
    ["Testing with unrealistic data volumes/distributions",
     "Measuring averages and ignoring tail latency",
     "One-off testing with no baseline or regression"],
    [("perf-test-plan", "Performance Test Plan"), ("workload-model", "Workload Model")],
    ["p95/p99 vs target", "Max sustained throughput", "Error rate under load"])

add("testing", "e2e-testing",
    "End-to-End Testing",
    "Validate complete user journeys through the real system.",
    "Verify the system works for users across the whole stack on critical journeys — kept few, stable, and high-value because they're expensive.",
    ["Critical user-journey selection",
     "Stable selectors and resilient locators",
     "Test data, environment, and state management",
     "Flake reduction (waits, retries, isolation)",
     "Cross-browser/device and CI/parallelization"],
    ["E2E suite covering critical journeys",
     "Flake-control and data strategy",
     "CI integration plan"],
    ["E2E-testing everything instead of critical paths",
     "Brittle selectors (CSS/text) that break on UI tweaks",
     "Tolerating flaky e2e that erode trust in the suite"],
    [("e2e-plan", "E2E Test Plan"), ("journey-map", "Critical Journey Map")],
    ["Critical-journey coverage", "Flake rate", "Suite runtime"])

add("testing", "contract-testing",
    "Contract Testing",
    "Verify services honor their API/event contracts so independent deploys don't break consumers.",
    "Catch integration breakage before deploy without slow, flaky end-to-end environments. Use consumer-driven contracts so each provider knows exactly what its consumers depend on, and breaking changes fail in CI — essential once services, events, or teams multiply.",
    ["Consumer-driven contract definition (what each consumer actually uses)",
     "Provider verification against all consumer contracts in CI",
     "Contract broker/registry for sharing and versioning contracts",
     "API and message/event contract coverage (sync and async)",
     "Backward/forward compatibility and can-i-deploy gating",
     "Contract evolution, versioning, and deprecation workflow"],
    ["Consumer-driven contracts per consumer/provider pair",
     "Provider verification in CI with a can-i-deploy gate",
     "Contract broker/registry setup and versioning policy"],
    ["Relying on slow, flaky end-to-end tests instead of contracts",
     "Provider-defined contracts that ignore what consumers truly use",
     "Contracts not verified in CI, so they drift from reality"],
    [("contract", "Consumer-Driven Contract"), ("verification-plan", "Provider Verification Plan")],
    ["Breaking changes caught pre-deploy", "Contract coverage of integrations",
     "End-to-end test reduction", "Can-i-deploy gate pass rate"])

add("testing", "security-testing",
    "Security Testing",
    "Find vulnerabilities through systematic, layered security testing.",
    "Test the system for security weaknesses across the SDLC — SAST, DAST, dependency, and manual testing — mapped to known risk categories.",
    ["SAST, DAST, IAST, and dependency/SCA scanning",
     "OWASP Top 10 / ASVS-based test cases",
     "Authentication, authorization, and session testing",
     "Secrets, injection, and misconfiguration testing",
     "Penetration testing and findings triage"],
    ["Security test plan mapped to ASVS/OWASP",
     "Findings report with severity (CVSS)",
     "Remediation and retest plan"],
    ["Scanner-only testing with no manual logic testing",
     "Drowning in low-severity noise, missing critical issues",
     "Testing only at the end, not in CI/CD"],
    [("sec-test-plan", "Security Test Plan"), ("findings-report", "Findings Report")],
    ["Critical/high findings open", "Mean time to remediate", "Scan coverage"])


# ============================ DEVOPS & PLATFORM ============================

add("devops", "infra-design",
    "Infrastructure Design",
    "Design cloud/on-prem infrastructure for reliability, security, and cost.",
    "Lay out the foundational infrastructure — networking, compute, storage, environments — to meet reliability, security, and cost goals as code.",
    ["Environment topology (dev/stage/prod) and isolation",
     "Networking (VPC, subnets, routing, ingress/egress)",
     "Compute/storage selection and right-sizing",
     "High availability, multi-AZ/region, and DR posture",
     "Cost modeling, tagging, and infrastructure-as-code"],
    ["Infrastructure design document and diagram",
     "Environment and network topology",
     "Cost and HA/DR plan"],
    ["Click-ops infrastructure with no IaC or reproducibility",
     "Flat network with no segmentation",
     "No cost model — surprise cloud bills"],
    [("infra-design", "Infrastructure Design"), ("network-topology", "Network Topology")],
    ["Provisioning reproducibility", "Cost vs budget", "Availability SLA"])

add("devops", "docker-architecture",
    "Docker Architecture",
    "Build secure, small, reproducible container images.",
    "Define how images are built — base images, layering, multi-stage, security — so containers are small, fast, reproducible, and safe.",
    ["Base-image selection (distroless/slim) and pinning",
     "Multi-stage builds and layer/cache optimization",
     "Non-root, least-privilege, and image hardening",
     "Image scanning, SBOM, and signing",
     "Tagging, registry, and reproducibility"],
    ["Dockerfile standards and base-image policy",
     "Image build/scan/sign pipeline",
     "Tagging and registry conventions"],
    ["Running as root in the container",
     "Huge images from single-stage builds and dev deps",
     "Mutable `latest` tags with no provenance"],
    [("dockerfile-standards", "Dockerfile Standards"), ("image-policy", "Image Policy")],
    ["Image size", "Critical CVEs per image", "Build cache hit rate"])

add("devops", "docker-compose-design",
    "Docker Compose Design",
    "Design multi-container local/edge stacks with Compose, done right.",
    "Compose multi-service stacks for local dev and small deployments with healthchecks, networks, secrets, and parity to production.",
    ["Service composition, dependencies, and healthchecks",
     "Networks, volumes, and data persistence",
     "Environment/config and secret handling",
     "Resource limits and restart policies",
     "Dev/prod parity and override files"],
    ["Compose stack with healthchecks and limits",
     "Network/volume/secret layout",
     "Override strategy for environments"],
    ["Secrets hardcoded in the compose file",
     "No healthchecks — `depends_on` races at startup",
     "Dev compose drifting far from production reality"],
    [("compose-design", "Compose Stack Design"), ("compose-standards", "Compose Standards")],
    ["Startup reliability", "Local↔prod parity", "Time to spin up stack"])

add("devops", "kubernetes-planning",
    "Kubernetes Planning",
    "Plan a Kubernetes platform: workloads, scaling, security, and operations.",
    "Decide how workloads run on Kubernetes — resources, networking, scaling, security, and GitOps — so the platform is reliable and operable.",
    ["Workload modeling (Deployments/StatefulSets/Jobs) and resources",
     "Networking, ingress, and service mesh decisions",
     "Autoscaling (HPA/VPA/cluster) and capacity",
     "Security (RBAC, network policies, pod security, secrets)",
     "GitOps, observability, and upgrade strategy"],
    ["Kubernetes platform plan",
     "Resource/scaling and security model",
     "GitOps and operations plan"],
    ["No resource requests/limits — noisy neighbors and OOMs",
     "Cluster-admin RBAC handed out broadly",
     "Treating k8s as a goal rather than a fit-for-purpose tool"],
    [("k8s-plan", "Kubernetes Plan"), ("workload-spec", "Workload Spec")],
    ["Resource utilization", "Pod restart rate", "Upgrade success"])

add("devops", "nginx-reverse-proxy",
    "Nginx Reverse Proxy",
    "Configure a robust reverse proxy: routing, TLS, caching, and limits.",
    "Set up Nginx (or similar) as a reliable front door: routing, TLS termination, upstreams, caching, compression, and protection.",
    ["Server/location routing and upstream definitions",
     "TLS termination, HTTP/2-3, and security headers",
     "Load balancing, healthchecks, and failover",
     "Caching, compression, and buffering",
     "Rate limiting, timeouts, and request limits"],
    ["Nginx configuration with TLS and routing",
     "Upstream/load-balancing setup",
     "Security-header and rate-limit policy"],
    ["Weak TLS config and missing security headers",
     "No upstream healthchecks/timeouts — hung requests",
     "Default config exposing version and verbose errors"],
    [("nginx-config", "Nginx Configuration"), ("proxy-policy", "Proxy Policy")],
    ["TLS rating (SSL Labs)", "p95 proxy latency", "5xx rate"])

add("devops", "ssl-management",
    "SSL/TLS Management",
    "Manage certificates and TLS configuration securely and automatically.",
    "Keep TLS strong and certificates always-valid: automate issuance/renewal, enforce modern protocols, and prevent expiry outages.",
    ["Certificate lifecycle and automated renewal (ACME)",
     "Protocol/cipher hardening and HSTS",
     "Certificate storage, rotation, and inventory",
     "Wildcard/SAN, mTLS, and internal CA decisions",
     "Expiry monitoring and incident prevention"],
    ["TLS configuration standard",
     "Automated renewal and inventory",
     "Expiry monitoring/alerting"],
    ["Manual renewals that lapse and cause outages",
     "Legacy protocols/ciphers (TLS 1.0/1.1) enabled",
     "Untracked certs with no expiry alerting"],
    [("tls-policy", "TLS Policy"), ("cert-inventory", "Certificate Inventory")],
    ["Cert expiry incidents", "TLS grade", "% auto-renewed"])

add("devops", "ci-cd-pipeline",
    "CI/CD Pipeline",
    "Design automated build-test-deploy pipelines that are fast and safe.",
    "Automate the path from commit to production with quality gates, security checks, and safe deployment strategies that enable frequent, low-risk releases.",
    ["Pipeline stages (build, test, scan, package, deploy)",
     "Quality and security gates (lint, tests, SAST, SCA)",
     "Artifact management and environment promotion",
     "Deployment strategies (blue-green, canary, rollback)",
     "Pipeline speed, caching, and observability"],
    ["CI/CD pipeline design and config",
     "Quality/security gate definitions",
     "Deployment and rollback strategy"],
    ["Deploying without automated rollback",
     "Gates so slow developers bypass them",
     "Secrets exposed in pipeline logs/config"],
    [("pipeline-design", "Pipeline Design"), ("deploy-strategy", "Deployment Strategy")],
    ["Lead time for changes", "Deploy frequency", "Change failure rate"])

add("devops", "observability-design",
    "Observability Design",
    "Design logs, metrics, and traces that make the system debuggable.",
    "Make the system understandable in production: structured logs, useful metrics, distributed traces, and SLOs — so you can answer 'what's wrong?' fast.",
    ["The three pillars: structured logs, metrics, traces",
     "SLI/SLO definition and error budgets",
     "Correlation IDs and distributed tracing",
     "Dashboards, alerting, and signal-to-noise",
     "Cardinality, retention, and cost management"],
    ["Observability design (logs/metrics/traces)",
     "SLI/SLO and alerting plan",
     "Dashboard and instrumentation standards"],
    ["Logging everything as unstructured text",
     "Alerting on causes, not symptoms — alert fatigue",
     "High-cardinality metrics that explode cost"],
    [("observability-design", "Observability Design"), ("slo-spec", "SLI/SLO Spec")],
    ["MTTD/MTTR", "Alert precision", "Trace coverage"])

add("devops", "backup-recovery",
    "Backup & Recovery",
    "Design backups that are complete, tested, and actually restorable.",
    "Protect against data loss with a backup strategy defined by RPO/RTO, encrypted and offsite, and — critically — regularly restore-tested.",
    ["RPO/RTO definition per data set",
     "Backup scope, frequency, and retention",
     "Encryption, immutability, and offsite/air-gap copies",
     "Restore testing and verification",
     "Automation, monitoring, and the 3-2-1 rule"],
    ["Backup & recovery plan with RPO/RTO",
     "Backup schedule and retention policy",
     "Restore-test procedure and results"],
    ["Backups that are never restore-tested",
     "Backups stored with (and deletable by) the same credentials",
     "No immutability — ransomware encrypts the backups too"],
    [("backup-plan", "Backup & Recovery Plan"), ("restore-runbook", "Restore Runbook")],
    ["Restore success rate", "Actual RPO/RTO vs target", "Backup coverage"])

add("devops", "server-hardening",
    "Server Hardening",
    "Reduce attack surface on hosts via baseline secure configuration.",
    "Lock down servers to a security baseline: minimize services, enforce least privilege, patch, and audit — reducing what an attacker can reach.",
    ["OS baseline and CIS-benchmark alignment",
     "Account, SSH, and least-privilege configuration",
     "Service minimization and firewall/host rules",
     "Patch management and automatic updates",
     "Audit logging, file integrity, and intrusion detection"],
    ["Hardening baseline/standard",
     "Compliance scan results vs benchmark",
     "Patch and audit plan"],
    ["Default passwords/ports and unused services left on",
     "Root/password SSH login enabled",
     "One-time hardening with no drift detection"],
    [("hardening-baseline", "Hardening Baseline"), ("cis-checklist", "CIS Checklist")],
    ["CIS benchmark score", "Patch latency", "Open-port count"])

add("devops", "secrets-management",
    "Secrets Management",
    "Store, rotate, and access secrets securely across the lifecycle.",
    "Eliminate plaintext secrets: centralize storage, scope access, rotate regularly, and audit usage so a leak is contained and recoverable.",
    ["Secret store selection (a dedicated secrets manager or cloud KMS)",
     "Dynamic/short-lived secrets and rotation",
     "Access control, scoping, and auditing",
     "Injection into apps/CI without exposure",
     "Leak detection and revocation procedures"],
    ["Secrets management design and policy",
     "Rotation and access model",
     "Leak-response procedure"],
    ["Secrets in git, env files, or CI variables in plaintext",
     "Long-lived static secrets never rotated",
     "No audit trail of who accessed what"],
    [("secrets-policy", "Secrets Policy"), ("rotation-plan", "Rotation Plan")],
    ["% secrets in a managed store", "Rotation compliance", "Leak MTTR"])

add("devops", "disaster-recovery",
    "Disaster Recovery",
    "Plan for surviving major failures with tested recovery procedures.",
    "Prepare for the worst — region loss, data corruption, ransomware — with a tested DR plan defining RPO/RTO, failover, and the runbook to execute under pressure.",
    ["Business impact analysis and RPO/RTO per system",
     "DR strategy (backup-restore, pilot-light, warm/hot standby)",
     "Failover/failback procedures and dependencies",
     "DR drills and game-day testing",
     "Communication plan and decision authority"],
    ["DR plan with RPO/RTO and strategy",
     "Failover/failback runbooks",
     "DR drill results"],
    ["A DR plan that has never been drilled",
     "Recovery depending on the very system that's down",
     "Undefined decision authority — paralysis during the disaster"],
    [("dr-plan", "Disaster Recovery Plan"), ("dr-runbook", "DR Runbook")],
    ["Drill RTO/RPO vs target", "Drill cadence", "Runbook accuracy"])

add("devops", "infrastructure-as-code",
    "Infrastructure as Code",
    "Manage infrastructure declaratively, reviewed and versioned like software.",
    "Make infrastructure reproducible and auditable: declarative definitions, modules, state management, and CI so changes are reviewed and reversible.",
    ["Declarative IaC tool/approach selection and repository structure",
     "Module design, reuse, and DRY composition",
     "State management, locking, and drift detection",
     "Environment separation and promotion",
     "Policy-as-code, plan review, and CI/CD integration"],
    ["IaC structure and module standards",
     "State and environment strategy",
     "Plan-review and policy-as-code gates"],
    ["Manual changes that cause state drift",
     "Copy-paste per environment instead of modules",
     "Applying without reviewing the plan"],
    [("iac-standards", "IaC Standards"), ("module-spec", "Module Spec")],
    ["% infra under IaC", "Drift incidents", "Apply success rate"])


# ============================ SECURITY & COMPLIANCE ============================

add("security", "threat-modeling",
    "Threat Modeling",
    "Systematically identify threats and design controls before building.",
    "Find out what can go wrong before attackers do: decompose the system, enumerate threats (STRIDE), and define controls during design.",
    ["System decomposition and data-flow diagrams",
     "Trust boundaries and attack-surface mapping",
     "STRIDE/PASTA threat enumeration",
     "Risk rating (DREAD/CVSS) and prioritization",
     "Control/mitigation design and validation"],
    ["Threat model with DFD and trust boundaries",
     "Enumerated threats with risk ratings",
     "Mitigation/control plan"],
    ["Threat modeling once at the start, never updated",
     "Listing threats with no mitigations or owners",
     "Modeling the diagram, not how it's really deployed"],
    [("threat-model", "Threat Model"), ("dfd", "Data-Flow Diagram")],
    ["Threats mitigated vs accepted", "Findings caught pre-production"])

add("security", "compliance-audit",
    "Compliance Audit",
    "Assess and evidence compliance against a framework (SOC2, ISO, GDPR, HIPAA).",
    "Determine where you stand against a compliance framework, close the gaps, and produce the evidence auditors require.",
    ["Framework scoping (SOC2, ISO 27001, GDPR, HIPAA, PCI)",
     "Control mapping and gap analysis",
     "Evidence collection and audit trails",
     "Policy/procedure documentation",
     "Remediation tracking and continuous compliance"],
    ["Compliance gap-analysis report",
     "Control-to-evidence mapping",
     "Remediation plan with owners"],
    ["Checkbox compliance with no real control behind it",
     "Scrambling for evidence at audit time, not continuously",
     "Treating compliance as one-and-done vs ongoing"],
    [("gap-analysis", "Compliance Gap Analysis"), ("control-matrix", "Control Matrix")],
    ["Controls implemented vs required", "Audit findings", "Evidence freshness"])

add("security", "vulnerability-management",
    "Vulnerability Management",
    "Continuously find, prioritize, and remediate vulnerabilities.",
    "Run the lifecycle that keeps known vulnerabilities under control: discover, prioritize by real risk, remediate within SLA, and verify.",
    ["Asset inventory and scanning (infra, app, dependencies)",
     "Risk-based prioritization (CVSS, EPSS, exploitability, exposure)",
     "Remediation SLAs and patch workflow",
     "Exception/risk-acceptance process",
     "Metrics, trending, and verification"],
    ["Vulnerability management process",
     "Prioritized remediation backlog with SLAs",
     "Metrics and reporting"],
    ["Prioritizing by CVSS alone, ignoring exploitability/exposure",
     "Scanning without a remediation workflow behind it",
     "Risk acceptances that never expire or get reviewed"],
    [("vm-process", "Vulnerability Management Process"), ("remediation-sla", "Remediation SLA")],
    ["Mean time to remediate", "% within SLA", "Open critical vulns"])

add("security", "access-control-design",
    "Access Control Design",
    "Design authorization models that enforce least privilege.",
    "Decide who can do what: choose the model (RBAC/ABAC/ReBAC), enforce least privilege and separation of duties, and make access auditable and reviewable.",
    ["Authorization model selection (RBAC, ABAC, ReBAC)",
     "Least privilege, separation of duties, and role design",
     "Policy enforcement points and centralization",
     "Privileged access and just-in-time elevation",
     "Access reviews, recertification, and audit"],
    ["Access control model and policy",
     "Role/permission matrix",
     "Access-review and audit process"],
    ["Role explosion or one god-role everyone gets",
     "Authorization scattered and inconsistent across services",
     "Access granted and never reviewed or revoked"],
    [("access-model", "Access Control Model"), ("rbac-matrix", "Role/Permission Matrix")],
    ["Least-privilege coverage", "Orphan/excess access found", "Review cadence"])


# ============================ MAINTENANCE & OPERATIONS ============================

add("maintenance", "troubleshooting",
    "Troubleshooting",
    "Diagnose problems methodically from symptom to root cause.",
    "Resolve issues efficiently with a repeatable method: reproduce, gather evidence, form and test hypotheses, fix, and verify — not guess-and-check.",
    ["Reproduction and symptom characterization",
     "Evidence gathering (logs, metrics, traces, state)",
     "Hypothesis-driven, binary-search isolation",
     "Root-cause vs symptom distinction",
     "Fix verification and knowledge capture"],
    ["Diagnosis writeup (symptom → root cause)",
     "Verified fix",
     "Runbook/knowledge-base entry"],
    ["Changing many things at once so the real cause stays hidden",
     "Fixing the symptom and leaving the root cause",
     "Not capturing the lesson — the same issue recurs"],
    [("troubleshooting-guide", "Troubleshooting Guide"), ("diagnosis-log", "Diagnosis Log")],
    ["Mean time to resolve", "Recurrence rate", "First-contact resolution"])

add("maintenance", "bug-investigation",
    "Bug Investigation",
    "Investigate bugs to a confirmed root cause with a regression test.",
    "Go beyond a quick patch: reproduce reliably, find the true root cause, fix it, and add a regression test so it never returns.",
    ["Reliable reproduction and minimal test case",
     "Root-cause analysis (5 whys, bisection, debugging)",
     "Impact/blast-radius and severity assessment",
     "Fix design with regression test",
     "Related-defect search and prevention"],
    ["Bug report with confirmed root cause",
     "Fix plus regression test",
     "Prevention/related-issue notes"],
    ["Patching the stack trace location, not the cause",
     "No regression test — the bug silently returns",
     "Not checking whether the same bug exists elsewhere"],
    [("bug-report", "Bug Investigation Report"), ("rca", "Root-Cause Analysis")],
    ["Reopen rate", "Time to root cause", "Regression-test coverage"])

add("maintenance", "refactoring-planning",
    "Refactoring Planning",
    "Plan safe, incremental refactors that improve code without changing behavior.",
    "Improve internal quality without breaking behavior: identify targets by pain and risk, ensure test coverage, and refactor in small, reversible steps.",
    ["Target identification (hotspots, complexity, churn)",
     "Behavior-preservation via test coverage first",
     "Incremental strangler/branch-by-abstraction strategy",
     "Risk assessment and rollback points",
     "Measuring improvement and avoiding scope creep"],
    ["Refactoring plan with sequenced steps",
     "Coverage/safety-net assessment",
     "Before/after quality metrics"],
    ["Big-bang rewrites disguised as refactoring",
     "Refactoring without tests to catch behavior changes",
     "Mixing refactoring and feature changes in one commit"],
    [("refactor-plan", "Refactoring Plan"), ("hotspot-analysis", "Hotspot Analysis")],
    ["Complexity reduction", "Defect rate in refactored areas", "Change lead time"])

add("maintenance", "migration-planning",
    "Migration Planning",
    "Plan low-risk migrations (data, platform, version) with rollback.",
    "Move from A to B safely: assess scope and risk, choose a strategy, sequence in reversible phases, and define validation and rollback at each step.",
    ["Scope, dependency, and compatibility assessment",
     "Strategy selection (big-bang, phased, parallel-run, strangler)",
     "Data migration, validation, and reconciliation",
     "Cutover plan, rollback, and contingency",
     "Coexistence period and decommissioning"],
    ["Migration plan with phases and rollback",
     "Data migration and validation approach",
     "Cutover runbook"],
    ["Big-bang cutover with no rollback path",
     "No data validation/reconciliation after migration",
     "Decommissioning the old system before the new one is proven"],
    [("migration-plan", "Migration Plan"), ("cutover-runbook", "Cutover Runbook")],
    ["Migration success rate", "Data reconciliation accuracy", "Rollback readiness"])

add("maintenance", "release-planning",
    "Release Planning",
    "Coordinate releases so changes ship predictably and safely.",
    "Get changes to users with minimal risk: define scope, versioning, the release process, communication, and rollback so releases are routine, not heroic.",
    ["Release scope, versioning (semver), and changelog",
     "Release process and approval gates",
     "Deployment strategy and feature flagging",
     "Communication, release notes, and stakeholder sign-off",
     "Rollback criteria and post-release verification"],
    ["Release plan and checklist",
     "Versioning and changelog",
     "Rollback and comms plan"],
    ["Big, infrequent releases that bundle high risk",
     "No clear rollback criteria or owner",
     "Surprising users/stakeholders with unannounced changes"],
    [("release-plan", "Release Plan"), ("release-checklist", "Release Checklist")],
    ["On-time release rate", "Change failure rate", "Rollback frequency"])

add("maintenance", "documentation-generator",
    "Documentation Generator",
    "Produce and maintain documentation that stays useful and current.",
    "Create docs people actually use — task-oriented, accurate, and maintained — and put them where they won't rot, close to the code and process that generates them.",
    ["Documentation types (Diátaxis: tutorial/how-to/reference/explanation)",
     "Audience analysis and information architecture",
     "Docs-as-code and generation from source/specs",
     "Style, examples, and accuracy review",
     "Freshness, ownership, and lifecycle"],
    ["Documentation set fit to audience",
     "Docs-as-code/generation setup",
     "Ownership and review cadence"],
    ["Writing docs nobody reads instead of what users need",
     "Docs that drift from the code with no review process",
     "One giant doc instead of task-oriented pieces"],
    [("doc-plan", "Documentation Plan"), ("doc-template", "Document Template")],
    ["Docs freshness", "Doc-related support tickets", "Time-to-first-success for new users"])

add("maintenance", "incident-response",
    "Incident Response",
    "Respond to production incidents with structure, then learn from them.",
    "Handle incidents calmly and consistently: detect, classify, mobilize roles, mitigate, communicate, and run a blameless postmortem that drives fixes.",
    ["Severity classification and escalation",
     "Roles (incident commander, comms, ops) and runbooks",
     "Mitigation, communication, and status updates",
     "Coordination, timeline, and decision logging",
     "Blameless postmortem and action-item follow-through"],
    ["Incident response plan and severity matrix",
     "Role definitions and runbooks",
     "Postmortem template and tracked actions"],
    ["No defined incident commander — chaotic response",
     "Blame culture that suppresses learning",
     "Postmortems with action items nobody completes"],
    [("ir-plan", "Incident Response Plan"), ("postmortem", "Postmortem")],
    ["MTTA/MTTR", "% postmortem actions completed", "Repeat-incident rate"])

add("maintenance", "monitoring-alerting",
    "Monitoring & Alerting",
    "Design alerts that fire on real, actionable problems — and nothing else.",
    "Catch problems before users do without drowning the team: alert on symptoms tied to SLOs, make every alert actionable, and continuously tune.",
    ["SLI/SLO-based, symptom-oriented alerting",
     "Alert thresholds, severity, and routing",
     "Actionability, runbooks, and ownership per alert",
     "Noise reduction (dedup, grouping, suppression)",
     "On-call, escalation, and alert review"],
    ["Alerting plan tied to SLOs",
     "Alert catalog with runbooks and owners",
     "On-call/escalation policy"],
    ["Alerting on causes/low-level metrics, not user symptoms",
     "Alerts with no runbook or clear action",
     "Alert fatigue from noisy, non-actionable alerts"],
    [("alerting-plan", "Alerting Plan"), ("alert-catalog", "Alert Catalog")],
    ["Alert precision (actionable %)", "Pages per on-call shift", "MTTD"])

add("maintenance", "technical-debt-management",
    "Technical Debt Management",
    "Make technical debt visible, prioritized, and paid down deliberately.",
    "Stop debt from compounding silently: inventory it, quantify its cost and risk, prioritize, and budget continuous paydown alongside feature work.",
    ["Debt inventory, classification, and tagging",
     "Cost/risk/interest quantification",
     "Prioritization (impact vs effort, hotspots)",
     "Paydown budgeting and the boy-scout rule",
     "Prevention, standards, and tracking"],
    ["Technical debt register with impact/effort",
     "Prioritized paydown plan and budget",
     "Prevention guidelines"],
    ["Debt that's invisible because it's never written down",
     "Either ignoring debt or stop-the-world rewrites",
     "No paydown budget — debt only ever grows"],
    [("debt-register", "Technical Debt Register"), ("paydown-plan", "Paydown Plan")],
    ["Debt trend over time", "% capacity on paydown", "Defect density in high-debt areas"])


add("maintenance", "code-simplicity-and-reuse",
    "Code Simplicity & Reuse",
    "Choose the simplest solution and reuse before writing new code (KISS, DRY, YAGNI).",
    "Keep the codebase small, simple, and DRY. Before writing code, check whether it already exists or isn't needed yet, and always prefer the simplest design that satisfies the requirement — because the cheapest, most reliable, and most maintainable code is the code you never wrote. This skill is language- and framework-agnostic: it governs decisions, not syntax.",
    ["Reuse-first: search the codebase, standard library, and existing modules before writing new code (DRY)",
     "YAGNI: build only what a current, real requirement needs — defer the speculative",
     "KISS: choose the simplest design that meets the requirement; treat any added complexity as something to justify",
     "Right abstraction timing: tolerate duplication until the shared concept is proven (rule of three) — a wrong abstraction costs more than repetition",
     "Subtract: remove dead code, redundant layers, needless configuration, and unused flags",
     "Readability over cleverness: optimize for the next reader, not for fewer lines or a trick"],
    ["Simplicity & reuse review notes (what was reused, simplified, or deleted, with rationale)",
     "A short project simplicity guideline (the codebase's DRY/KISS/YAGNI rules)",
     "A reuse index of shared utilities and where to find them"],
    ["Copy-pasting logic into a third place instead of extracting it",
     "Adding abstraction or configuration for an imagined future requirement",
     "Choosing a clever solution over a clear one"],
    [("simplicity-review", "Simplicity & Reuse Review"), ("simplicity-guideline", "Simplicity Guideline")],
    ["Net lines of code (added minus removed)", "Code duplication / clone ratio (%)",
     "Cyclomatic complexity trend", "Reuse rate of shared utilities"])


# ============================ DOMAIN EXPANSION (any-system readiness) ============================

add("product", "product-analytics",
    "Product Analytics",
    "Instrument product analytics and event tracking so decisions are evidence-based.",
    "Define what to measure and how, so the team can answer product questions with reliable, privacy-respecting behavioral data instead of opinions.",
    ["Tracking plan: events, properties, naming conventions, and ownership",
     "North-star and funnel/retention/cohort metric design",
     "Client vs server-side instrumentation and identity resolution",
     "Privacy, consent, and PII minimization in analytics",
     "Data quality, validation, and governance of the event stream"],
    ["Versioned tracking plan with event schema",
     "Funnel, retention, and activation metric definitions",
     "Instrumentation + QA checklist for events"],
    ["Tracking everything 'just in case' — unusable, costly noise",
     "Inconsistent event names that break analysis",
     "Capturing PII without consent or minimization"],
    [("tracking-plan", "Tracking Plan"), ("metric-definitions", "Metric Definitions")],
    ["% of events conforming to the tracking plan", "Time-to-answer for product questions"])

add("architecture", "realtime-architecture",
    "Realtime Architecture",
    "Design realtime systems — websockets, SSE, pub/sub, and presence — that stay consistent under load.",
    "Decide how live updates flow to clients reliably and at scale, choosing transport, fan-out, and consistency trade-offs deliberately rather than bolting sockets on later.",
    ["Transport choice: WebSocket vs SSE vs long-poll vs WebTransport",
     "Fan-out and pub/sub topology, presence, and connection state",
     "Ordering, delivery guarantees, backpressure, and reconnection",
     "Horizontal scaling of stateful connections and sticky routing",
     "Authn/authz on persistent connections and message authorization"],
    ["Realtime transport and topology decision (ADR)",
     "Delivery-guarantee and reconnection/backpressure plan",
     "Scaling and connection-state design"],
    ["Assuming sockets scale like stateless HTTP",
     "No reconnection/replay strategy — clients silently drift",
     "Broadcasting to everyone instead of scoped channels"],
    [("realtime-design", "Realtime Design"), ("delivery-guarantees", "Delivery Guarantees Plan")],
    ["P99 message delivery latency", "Reconnect success rate", "Messages dropped under load"])

add("frontend", "internationalization",
    "Internationalization & Localization",
    "Design i18n/l10n: locales, translations, formatting, and right-to-left from the start.",
    "Make the product translatable and culturally correct without re-engineering, by separating content from code and handling locale-aware formatting and layout up front.",
    ["Locale strategy, fallback chains, and language negotiation",
     "Externalized strings, ICU message format, and pluralization",
     "Date/number/currency formatting and time zones",
     "Right-to-left layout, bidi text, and locale-aware UI",
     "Translation workflow, TMS integration, and pseudo-localization"],
    ["i18n architecture and locale strategy",
     "Translation/extraction workflow and catalog format",
     "RTL and formatting test checklist"],
    ["Concatenating translated strings — grammatically broken",
     "Hardcoding date/number/currency formats",
     "Ignoring RTL and text-expansion until launch"],
    [("i18n-strategy", "i18n Strategy"), ("translation-workflow", "Translation Workflow")],
    ["% of UI strings externalized", "Locale coverage", "Layout defects per locale"])

add("backend", "payments-billing",
    "Payments & Billing",
    "Design payments, subscriptions, invoicing, and billing that are correct, auditable, and PCI-aware.",
    "Handle money safely: integrate providers, model subscriptions and invoices, reconcile, and stay compliant — where bugs mean lost revenue, fraud, or legal exposure.",
    ["Provider integration (Stripe/Adyen/etc.) and PCI scope minimization",
     "Subscription, metering, proration, tax, and invoicing models",
     "Idempotency, webhooks, retries, and reconciliation",
     "Dunning, refunds, chargebacks, and revenue recognition",
     "Ledger design, auditability, and money/currency precision"],
    ["Billing/subscription data model and ledger design",
     "Provider integration + webhook/idempotency plan",
     "Reconciliation, refund, and dunning runbook"],
    ["Storing card data and expanding PCI scope needlessly",
     "Floating-point money or missing currency precision",
     "Non-idempotent payment handlers — double charges"],
    [("billing-design", "Billing Design"), ("reconciliation-plan", "Reconciliation Plan")],
    ["Payment success rate", "Billing discrepancy rate", "Involuntary churn from dunning"])

add("backend", "notification-system",
    "Notification System",
    "Design multi-channel notifications — email, push, SMS, in-app — that are reliable and not annoying.",
    "Deliver the right message on the right channel at the right time, with user preferences, deliverability, and rate limiting handled as first-class concerns.",
    ["Channel strategy (email, push, SMS, in-app) and provider selection",
     "Template/content management, localization, and personalization",
     "User preferences, consent, quiet hours, and unsubscribe",
     "Delivery reliability: queues, retries, idempotency, dedup",
     "Deliverability, rate limiting, batching, and digesting"],
    ["Notification architecture and channel routing design",
     "Preference/consent model and template system",
     "Delivery reliability and rate-limit plan"],
    ["Sending duplicate or storm notifications on retries",
     "Ignoring user preferences, consent, and quiet hours",
     "No deliverability handling — landing in spam"],
    [("notification-design", "Notification Design"), ("preference-model", "Preference Model")],
    ["Delivery success rate per channel", "Opt-out rate", "Notification-driven engagement"])

add("backend", "api-gateway-design",
    "API Gateway Design",
    "Design an API gateway: routing, auth, rate limiting, versioning, and observability at the edge.",
    "Put a deliberate front door on your services — centralizing cross-cutting concerns like auth, throttling, and routing without turning the gateway into a fragile monolith.",
    ["Routing, aggregation, and protocol translation (REST/gRPC/GraphQL)",
     "Edge authn/authz, key management, and token validation",
     "Rate limiting, quotas, throttling, and circuit breaking",
     "Versioning, canary routing, and request/response transformation",
     "Edge observability, tracing propagation, and WAF integration"],
    ["Gateway routing and policy design",
     "Edge auth, rate-limit, and quota plan",
     "Versioning and canary routing strategy"],
    ["Putting business logic in the gateway — a new monolith",
     "No rate limiting — one client can starve the rest",
     "Breaking clients with unversioned routing changes"],
    [("gateway-design", "Gateway Design"), ("edge-policy", "Edge Policy Plan")],
    ["Edge P99 latency overhead", "Rate-limit accuracy", "Auth failures at the edge"])

add("maintenance", "feature-flag-management",
    "Feature Flag Management",
    "Manage feature flags, gradual rollout, and experimentation without flag debt or surprises.",
    "Decouple deploy from release so changes ship safely behind flags — with rollout control, targeting, and disciplined cleanup so flags don't rot into permanent complexity.",
    ["Flag types (release, ops, experiment, permission) and lifecycle",
     "Targeting, segmentation, and gradual/percentage rollout",
     "Kill switches, defaults, and fail-safe evaluation",
     "Experimentation/A-B integration and metrics",
     "Flag debt: ownership, expiry, and systematic cleanup"],
    ["Flag taxonomy and lifecycle policy",
     "Rollout, targeting, and kill-switch plan",
     "Flag cleanup/expiry process"],
    ["Flags that never get removed — permanent dead branches",
     "No default/fail-safe when the flag service is down",
     "Testing only one side of the flag"],
    [("flag-policy", "Flag Policy"), ("rollout-plan", "Rollout Plan")],
    ["Stale flag count and age", "Rollout-related incident rate", "Flag cleanup throughput"])


# ---------------------------------------------------------------------------
# Flatten into the list the engine expects.
# ---------------------------------------------------------------------------

def build_skills():
    skills = []
    for cat_slug, entries in R.items():
        for slug, e in entries.items():
            skills.append({
                "slug": slug,
                "category_slug": cat_slug,
                "category_title": CATEGORIES[cat_slug],
                "title": e["t"],
                "desc": e["d"],
                "purpose": e["p"],
                "focus": e["f"],
                "deliverables": e["dl"],
                "antipatterns": e["ap"],
                "templates": e["tpl"],
                "metrics": e["m"],
                "tags": [],
            })
    return skills


ALL_SKILLS = build_skills()

if __name__ == "__main__":
    print(f"Defined {len(ALL_SKILLS)} skills across {len(R)} categories")
    from collections import Counter
    c = Counter(s["category_slug"] for s in ALL_SKILLS)
    for cat, n in c.items():
        print(f"  {cat}: {n}")
